### ISSUE TITLE
Bump the axios version

### ISSUE THREAD

**Issue by mateutek** [Pewtro/blizzard-api#31]
Hi, 
Can you bump the axios version, as there was a bug that is breaking the cloudflare deployment
https://github.com/axios/axios/issues/6565

**Comment by Pewtro** [comment]
I released 1.0.8 of `@blizzard-api/client` that should address this, let me know if it doesn't!

**Comment by mateutek** [comment]
I bumped it locally with override for axios, and it helped.
There was also some problem od cloudflare  with .unref()
For now i forked the repo and put the files locally while comenting out those two unrefs and it started to work properly.
No idea what the problem is, locally it was working fine.

**Comment by Pewtro** [comment]
I released `1.0.9` that should solve an issue with unref and electron, perhaps it fixes your issue with cloudflare too?
