### ISSUE TITLE
TypeError: setInterval(...).unref - Electron compatibility

### ISSUE THREAD

**Issue by FlaviaSo** [Pewtro/blizzard-api#32]
Hey! Since there is this issue with Electron and Node.js compatibility, I was wondering if it was possible to add a workaround for the TypeError: setInterval(...).unref problem mentioned [here](https://github.com/electron/electron/issues/21162#issuecomment-554792447).

Thank you!

**Comment by Pewtro** [comment]
Why in the world is electron overriding the base setTimeout global...

Can you try `1.0.9` that should be released shortly?
